/* Disposable manual goal/review example. No API, storage or member calls. */
(function(){
  'use strict';
  var area=document.getElementById('demo-next-move');if(!area)return;
  var zone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',now=new Date(),today=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
  var draft=[],saved=null,briefSteps=[],briefDraft=[{body:'read the brief and choose an idea',date:''},{body:'finish a small pack for the brief',date:''},{body:'submit through this brief’s page',date:''}],working=false,pursued=false,submissions=[],interest=false,completedRecords=new Map(),nextId=1;
  function get(id){return document.getElementById(id);}
  function el(tag,text,cls){var node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
  function clone(value){return JSON.parse(JSON.stringify(value));}
  function button(text,action){var node=el('button',text,'d-text-button');node.type='button';node.addEventListener('click',action);return node;}
  function openSection(index){get('dt-'+index).click();get('dp-'+index).scrollIntoView({block:'start',behavior:'instant'});}
  function fields(parent,label,value,max,onInput,type,id){var name=el('label',label);name.htmlFor=id;var input=el('input',undefined,'d-input');input.id=id;input.type=type||'text';input.value=value;input.maxLength=max;if(input.type==='text')input.required=true;input.addEventListener('input',function(){onInput(input.value);});parent.append(name,input);}
  function stepEditor(parent,steps,prefix,redraw){parent.replaceChildren();steps.forEach(function(step,i){var box=el('div',undefined,'d-next-step');fields(box,'step '+(i+1),step.body,140,function(value){step.body=value;},'text',prefix+'-body-'+i);fields(box,'your date (optional)',step.date||'',10,function(value){step.date=value;},'date',prefix+'-date-'+i);if(steps.length>1)box.append(button('remove step '+(i+1),function(){steps.splice(i,1);redraw();}));parent.append(box);});}
  function renderDraft(){var editor=get('demo-focus-editor');editor.replaceChildren();draft.forEach(function(focus,i){var box=el('fieldset',undefined,'d-next-focus');box.append(el('legend','focus '+(i+1)));fields(box,'one specific focus',focus.title,120,function(value){focus.title=value;},'text','demo-focus-'+i);var steps=el('div');stepEditor(steps,focus.steps,'demo-focus-'+i,renderDraft);box.append(steps);if(focus.steps.length<8)box.append(button('add a step',function(){focus.steps.push({body:'',date:''});renderDraft();}));if(draft.length>1)box.append(button('remove focus '+(i+1),function(){draft.splice(i,1);renderDraft();}));editor.append(box);});get('demo-goal-actions').hidden=!draft.length;get('demo-goal-manual').hidden=!!draft.length;get('demo-focus-add').hidden=draft.length>=3;}
  function startingPoint(goal){var title='finish one small piece of work',steps=['name the piece you want to finish','work on it for one focused session','save or send the finished version'];if(/\b(placement|placements|brief|briefs|submit|submission|submissions)\b/i.test(goal)){title='prepare one brief submission';steps=['choose a current brief and read its requirements','finish one beat or small pack for those requirements','submit it through the brief page'];}else if(/\b(sell|selling|sales|income|money|earn|client|clients)\b/i.test(goal)){title='make one clear offer to an artist';steps=['choose one artist to contact','write a short message about what you can offer','send it and note what happened'];}else if(/\b(network|networking|connect|connections|relationship|relationships)\b/i.test(goal)){title='start one useful conversation';steps=['choose one person you want to work with','write a specific introduction or useful offer','send it and record the next action'];}else if(/\b(beat|beats|music|finish|finished|produce|production)\b/i.test(goal)){title='finish one beat you can share';steps=['choose one idea to finish','finish the arrangement and export it','save a shareable link and choose where to send it'];}return[{title:title,steps:steps.map(function(body){return{body:body,date:''};})}];}
  get('demo-goal-start').addEventListener('click',function(){if(!get('demo-goal').value.trim()){get('demo-goal').focus();return;}draft=startingPoint(get('demo-goal').value);renderDraft();get('demo-goal-notice').textContent='a starting point. edit it until it says what you want to do. nothing is saved yet.';});
  get('demo-goal-manual').addEventListener('click',function(){draft=[{title:'',steps:[{body:'',date:''}]}];renderDraft();});
  get('demo-focus-add').addEventListener('click',function(){if(draft.length<3){draft.push({title:'',steps:[{body:'',date:''}]});renderDraft();}});
  get('demo-goal-ai').addEventListener('click',function(){get('demo-ai-status').textContent='AI help is not available right now. use the editable starting point or write your own steps.';});
  function aiConsent(){get('demo-goal-ai').disabled=!get('demo-goal-consent').checked||!get('demo-goal').value.trim();}get('demo-goal-consent').addEventListener('change',aiConsent);get('demo-goal').addEventListener('input',aiConsent);
  function validSteps(steps){return steps.length>0&&steps.length<=8&&steps.every(function(step){return step.body.trim().length>0&&step.body.trim().length<=140&&(!step.date||/^\d{4}-\d{2}-\d{2}$/.test(step.date));});}
  function assignIds(steps){return steps.map(function(step){return Object.assign({},step,{id:step.id||nextId++,body:step.body.trim(),done:!!step.done});});}
  get('demo-goal-form').addEventListener('submit',function(event){event.preventDefault();var goal=get('demo-goal').value.trim();if(!goal||goal.length>280||draft.length<1||draft.length>3||draft.some(function(f){return!f.title.trim()||f.title.trim().length>120||!validSteps(f.steps);})){get('demo-goal-notice').textContent='didn’t save. check the fields and try again.';return;}saved={goal:goal,focuses:draft.map(function(f){return{title:f.title.trim(),steps:assignIds(f.steps)};})};draft=clone(saved.focuses);renderDraft();get('demo-goal-editor').querySelector('summary').textContent='edit your goal and focuses';get('demo-goal-editor').open=false;get('demo-goal-notice').textContent='your plan is saved. your next step is ready.';render();});
  function allSteps(){return(saved?saved.focuses.flatMap(function(f){return f.steps;}):[]).concat(briefSteps);}
  function nextStep(){return(saved?saved.focuses.flatMap(function(f){return f.steps;}):[]).find(function(s){return!s.done;})||(working?briefSteps.find(function(s){return!s.done;}):null);}
  function savedSteps(parent,steps){parent.replaceChildren();steps.forEach(function(step){var row=el('li'),label=el('label',undefined,'d-next-check'),check=el('input');check.type='checkbox';check.checked=step.done;check.addEventListener('change',function(){step.done=check.checked;var draftStep=draft.flatMap(function(f){return f.steps;}).concat(briefDraft).find(function(s){return s.id===step.id;});if(draftStep)draftStep.done=step.done;render();});var words=el('span',step.body);if(step.date)words.append(el('small','your date: '+step.date));label.append(check,words);row.append(label);parent.append(row);});}
  get('demo-next-done').addEventListener('click',function(){var next=nextStep();if(next){next.done=true;var step=draft.flatMap(function(f){return f.steps;}).concat(briefDraft).find(function(s){return s.id===next.id;});if(step)step.done=true;render();}});
  var guides=[{title:'How to Get Placements as a Music Producer',blurb:'The full 48-page industry guide. Portfolio, networking, targeting emerging artists, the business side in depth, negotiating, and the exact system behind real placements. Read it front to back.'},{title:'The Inner Game of Selling Beats',blurb:'The psychology and philosophy behind selling. How to think, position and carry yourself so artists and producers want to work with you.'},{title:'Artist Selling Guide',blurb:'Selling to artists the right way. Approaching, pitching and building the relationships that turn into placements and repeat work.'}];
  var stop=new Set(['want','would','like','more','this','month','year','with','make','some','goal','have','into','them','that','work','your']);function words(value){return Array.from(new Set(value.toLowerCase().match(/[a-z]{4,}/g)||[])).filter(function(w){return!stop.has(w);});}
  function renderSuggestions(){var parent=get('demo-suggestions');parent.replaceChildren();if(interest){parent.append(el('h4','example artist · illustrative Hip hop brief'),el('p','its listed sound, Hip hop, matches an interest you selected. read the brief to check the requirements.','d-small'),button('open example brief',function(){openSection(2);}));}else parent.append(el('p','save an interest to see briefs with the same listed sound.','d-small'));var sought=words(saved?saved.goal:'');var matches=guides.map(function(guide){var hay=words(guide.title+' '+guide.blurb);return{guide:guide,terms:sought.filter(function(term){return hay.some(function(word){return word.replace(/s$/,'')===term.replace(/s$/,'');});})};}).filter(function(match){return match.terms.length;}).sort(function(a,b){return b.terms.length-a.terms.length;}).slice(0,2);matches.forEach(function(match){parent.append(button(match.guide.title,function(){openSection(7);}),el('p','its title or description mentions '+match.terms.slice(0,2).join(' and ')+', which you mentioned in your goal.','d-small'));});if(!matches.length)parent.append(el('p','save a goal to see guides whose descriptions mention the same topics.','d-small'));}
  get('demo-interests-form').addEventListener('submit',function(event){event.preventDefault();interest=get('demo-interest').checked;get('demo-interest-disclosure').querySelector('summary').textContent='choose your interests · '+(interest?1:0)+' saved';get('demo-interest-status').textContent='your example interests are saved.';renderSuggestions();});
  function recordSteps(steps,prefix){steps.forEach(function(step){if(step.done)completedRecords.set(prefix+step.id,step.body);else completedRecords.delete(prefix+step.id);});}
  function render(){var next=nextStep();get('demo-next-title').textContent=next?next.body:saved?'your saved steps are done.':'give your goal a next step.';get('demo-next-date').textContent=next?(next.date?'your planned date: '+next.date:'no date set. choose one if it helps.'):'start small. you choose the focus, the steps and the dates.';get('demo-next-done').hidden=!next;var panel=get('demo-saved-plan');panel.hidden=!saved;panel.replaceChildren();if(saved){panel.append(el('h3',saved.goal));saved.focuses.forEach(function(f){panel.append(el('h4',f.title));var list=el('ul',undefined,'d-next-checklist');savedSteps(list,f.steps);panel.append(list);});panel.append(el('p','untick a step to undo a completion. dates are your plan, not a promise of a placement.','d-small'));}get('demo-working-brief').hidden=!working;savedSteps(get('demo-brief-saved'),briefSteps);recordSteps(allSteps(),'step-');var counts=get('demo-review-counts');counts.replaceChildren();[completedRecords.size+' tasks marked done',(pursued?1:0)+' briefs saved as working on',submissions.length+' submissions recorded'].forEach(function(text){counts.append(el('p',text));});var list=get('demo-review-completed');list.replaceChildren();completedRecords.forEach(function(body){list.append(el('li',body));});get('demo-review-next').textContent='next unfinished action: '+(next?next.body:'no approved step is waiting. choose a small next move.');renderSuggestions();}
  document.addEventListener('demo:tasks',function(event){recordSteps(event.detail,'quick-');render();});
  var monday=new Date(today+'T12:00:00Z');monday.setUTCDate(monday.getUTCDate()-(monday.getUTCDay()+6)%7);get('demo-review-range').textContent=monday.toISOString().slice(0,10)+' to '+today+', in '+zone;
  function renderBriefEditor(){stepEditor(get('demo-brief-step-editor'),briefDraft,'demo-brief',renderBriefEditor);get('demo-brief-add').hidden=briefDraft.length>=8;}
  get('demo-brief-add').addEventListener('click',function(){if(briefDraft.length<8){briefDraft.push({body:'',date:''});renderBriefEditor();}});
  get('demo-checklist-form').addEventListener('submit',function(event){event.preventDefault();if(!validSteps(briefDraft)){get('demo-checklist-status').textContent='didn’t save. check the fields and try again.';return;}briefSteps=assignIds(briefDraft);briefDraft=clone(briefSteps);renderBriefEditor();get('demo-brief-editor').querySelector('summary').textContent='edit checklist';get('demo-brief-editor').open=false;get('demo-checklist-status').textContent='checklist saved.';render();});
  var board=document.querySelector('#dp-2 .submission-preview'),work=el('div',undefined,'d-example-work');work.append(el('h4','example artist · illustrative Hip hop brief'),el('p','safe example only. its deadline is the illustrative date above; no placement is guaranteed.','d-small'));var workButton=button('save as working on',function(){working=!working;if(working)pursued=true;workButton.textContent=working?'stop working on this brief':'save as working on';workButton.setAttribute('aria-pressed',String(working));render();});workButton.setAttribute('aria-pressed','false');work.append(workButton,button('plan it in Your Day',function(){openSection(1);area.scrollIntoView({block:'start'});}));board.append(work);
  var deadline=document.querySelector('[data-brief-deadline]').textContent;get('demo-working-deadline').textContent=deadline?'example brief deadline: '+deadline:'no example deadline listed.';
  area.querySelectorAll('[data-demo-board],[data-demo-submit]').forEach(function(node){node.addEventListener('click',function(){openSection(2);board.scrollIntoView({block:'center'});});});
  get('demo-stop-brief').addEventListener('click',function(){working=false;workButton.textContent='save as working on';workButton.setAttribute('aria-pressed','false');render();});
  var form=el('form'),label=el('label','example submission link'),input=el('input',undefined,'d-input');label.htmlFor='demo-example-link';input.id='demo-example-link';input.type='url';input.value='https://example.invalid/music/my-example-pack';input.required=true;var submit=el('button','record example submission','d-pill d-pill-2');submit.type='submit';var status=el('p','','d-small');status.setAttribute('role','status');form.append(label,input,submit,status);board.append(el('p','this preview records an example only. it does not send a submission or email.','d-small'),form);
  var receipts=el('section',undefined,'d-box');receipts.setAttribute('aria-label','Example submissions');receipts.hidden=true;get('dp-3').append(receipts);
  form.addEventListener('submit',function(event){event.preventDefault();var link;try{link=new URL(input.value);if(link.protocol!=='https:'||link.hostname!=='example.invalid')throw new Error();}catch(_){status.textContent='use an https://example.invalid/ example link.';return;}submissions.push({link:link.href});receipts.hidden=false;receipts.append(el('p','example artist · new · example submission '+submissions.length,'d-small'));document.querySelector('#dp-3 .d-split .d-box').hidden=true;status.textContent='example submission recorded. no message or email was sent.';render();openSection(3);});
  get('demo-recap-zone').value=zone;for(var h=0;h<24;h++){var option=el('option',String(h).padStart(2,'0')+':00');option.value=h;get('demo-recap-hour').append(option);}get('demo-recap-hour').value='9';
  get('demo-recap-form').addEventListener('submit',function(event){event.preventDefault();try{new Intl.DateTimeFormat('en',{timeZone:get('demo-recap-zone').value});}catch(_){get('demo-recap-status').textContent='choose a valid timezone, such as Australia/Sydney.';return;}get('demo-recap-status').textContent=(get('demo-recap-opt').checked?'preference saved.':'weekly email preference is off.')+' email delivery remains disabled.';});
  renderDraft();renderBriefEditor();render();
})();
